workers: 5
batchSize: 80
batchTimeout: 10000
bounceTimeout: 5000

watchers:
  watcher-1:
    listen: "*"
    watchPath: "./test"
    processExisting: false
    recursive: true
    tag: test_tag
    exporters:
      - yandex-exporter
    deleteOnProcessEnd: true
